export type IKImage = {
  type: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  fileId: string;
  tags: unknown[];
  AITags: unknown[];
  embeddedMetadata: unknown[];
  customCoordinates: unknown[];
  customMetadata: object;
  isPrivateFile: boolean;
  url: string;
  thumbnail: string;
  fileType: string;
  filePath: string;
  height: number;
  width: number;
  size: number;
  hasAlpha: boolean;
  mime: string;
};
